spring:
  datasource:
    url: jdbc:h2:mem:testdb;
    username: sa
    password:
    data: import.sql
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false
api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}